#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbacdb?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#配置MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.woniuxy.model
