spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woniu_k15
    username: root
    password: 123456

server:
  port: 8084
#port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml